import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { NavigationMenuDemo } from "@/components/Home/Navbar";
import Footer from "@/components/Home/Footer";
import { Toaster } from 'react-hot-toast';
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};
export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        <div className="w-screen flex flex-col relative">
          {/* Navbar */}
          <div className="w-full flex justify-between items-center flex-shrink-0 h-16 fixed top-0 left-0 bg-blue-900/60 shadow z-[999]">
            <NavigationMenuDemo />
          </div>

          {/* Spacer so content is not under navbar */}
          <div className="h-16 flex-shrink-0" />

          {/* Page Content */}
          <main className="flex-1 flex flex-col">{children}</main>

          {/* Footer */}
          <Footer />
        </div>
        <Toaster />
      </body>
    </html>
  );
}

